language: go
env:
- GO111Module=on
go:
- 1.11.x
git:
  depth: 1
branches:
  only:
  - master
install: true
notifications:
  slack:
    rooms:
      secure: ad93KJjY2VyK3a4RFLvyXAXq6xFZm+2IqkO7vCGeetOxJrkk9P0MGqyDfc3nygRM9FU56XZBOjCgRCH7HPc7UelI50UGDTE8AEvzeN1SrDyCCOvIhVRWkajNCdPvQmmS957EUnMoe+yXaeLueir2f3grzXBBxWxSHi/ypH8Cb6mwR+xfmopIo9t/VDosP8YOmj99uwOJ8RBxTcDQomyvKNkmNO4DMgOpEVif8lDzQsbezN7YFbQ0DhIXuF2l7XBwLq+Pudzat8hAXOueiiseQWHE2Mu2xeIYGR2sHoM6lvnjbabxDrHaHMsVJdremo+v/MjCvm1rMwmLIF12p8QLVDWHzPvD/aehDFT+0mZehjNW24vSdoiUBNVSGozPiDDugEldD3dTAn5yoIwT7su6sns1LtlzdfIw/cUWKxrDL5Y7byOsMEmmUDdNU+Je8R2ywuZzjB8b4sX7LG72u07YV2x3XtSGc/Qinaamnfnfq9FZIznSMt/+4mlHCkRx75K4I0/lfH2UEocaO1TGoRXoY8iBBwABmExI0c///Z1n+z4NkJFkFS72ofVIN8kqqYuNDxyHdT/8+AIRfokRlCKooAUjufvn+Q/VpiTmKVkyBU4pwly381roEXVWrp811j1AmJSq7KluEZGHALw+IYuyoIP8pbe5kQ4/ucP8CjBAGd4=
    on_success: always
    on_failure: always
