language: go
env:
- GO111Module=on
go:
- 1.11.x
git:
  depth: 1
branches:
  only:
  - master
install: true
notifications:
  slack:
    rooms:
      secure: ay6Up/ceF8OkHzgBKo9qdwT6/n32bFftxmSqCKKRGAPodN7ToCG0vbiWZ8QZSaF5Dd9RcK52Y00TI2LJ0vMIDq8OzNIbbMRYxQlFTV3n+ByT1zFrThDzQgVL/YsBKUZPOUAtxRK8TyIHJqVgUXpHtYGxQSXurITcNqacCzTxbojvS/uXwh7Zx6RzK63Irvzz7JKmrgiSRvNrPL/x3BJS2pJq90+TAsT7dkvb3TEvTwmTtySAOgM+ZY2W2dzV3WFR32hEYRq4ofryMTBCKeUpNLM+ZU3E/5wc+fGeJLNKjZbkbIeiUq/P0BpCjYiNTCITskJfE/JcxHq/vEwuJQlPc90A7HkOWl0nGSe+PxlY4KOwAnOdjlQretekfr/81XO97ytTOnZRxtB0YsogkQBAA7raU/1OA/NTSnmeqmGa5R3Kcf9M2K/C+1Gpp3IUXDaIM0l28U72t/O2EqNS9VLhTbOhU1N+lHwScefR3R1mQOtsy5gqC7TWiL1O0UepsuEOKdhAfBKCrxznKCIAyypYlAps9lHMO+x74ZE4zFC11JVMGD1llTGwAheWrIjBu3io0pUorZFuwWj1FyvickuAwK4UnJzD7DYvvXm6fqEB76gqAZjm8QuehH3ghJIzuhrlIMDVgzJnlZ4QkrigZtoOf51KK9XaJI58o5Bx7HiNcc0=
    on_success: always
    on_failure: always
