language: go
env:
- GO111Module=on
go:
- 1.11.x
git:
  depth: 1
branches:
  only:
  - master
install: true
notifications:
  slack:
    secure: L+zlj9St2HajaMF2dTNqeF02ojkj0MCeFx0LpImyYIFHHYFVdGiuIJGKEXGU+8D5BOvjMOfkWIuwTyO5lUorcq1zSgvlDF01qr4nvicroftEcBK4RnWkVS9Q/p1qISyYDGplLtgwF+TSa08mJf8+8MTQ4GqA9g4ELIqqeUDEiwjVXr/138O65YDpE63IGeK69mEoOG4H9cmTEKlRe4MIj5AjpYpXeQcfG245NRsu9xKDJ2AmdM2ul5Ge44nI5p10q9FajOGErB7zgQGlHS77e/yUB0Oh4EFLNeHgvGbJm4AnRj3fqnbpZw7+of71dT+0aNeSKR0eVLYT5INeP8eKGvd0I+hh50JhCrPjDXHLFYLLDecfniMC40NYPa7HMXFL33tmusuz+7xVsaP7LobVlsIRaUmSMXVP8zIHVCxqlPDuEcPeH+Wz90hqnRHfMrseIoNCZ42wveYO9HjZRqzIiPw4llzgclePKXzkXvSORzRKFgyXLfBOOrEuJkE2o31Abo7XdXIyuxohlqstSM5Ag6yL04x7gA1nGDBwUtHjKV3p1LixsTNxDhs+YgxwltEVU2MuL1K28SzY8//BK64mVzMSvhaSI3NJtFhaU2LVROvQU5JzmYeQ1k6Z7CbuluQb1PggeU4j/YUWrCN/YU0vJGKrJmlqrpmUyfeRF2/JTlI=
